version: "3.9"
   
services:
  db:
    image: mysql/mysql-server:8.0.28
    ports:
      - 3306:3306                                                                                                                                  
    environment:                                                                                                                                   
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"                                                                                                             
